const initialState = {
  data: [
    {
      id: 33486,
      title: 'Boku No Hero Academia',
      linkCanonical: '',
      imageUrl: 'https://myanimelist.cdn-dena.com/images/anime/12/85221.jpg',
      synopsis: '',
      type: '',
      episodes: 24,
      status: 'Airing',
      aired: '',
      producer: ['Sunrise'],
      studio: ['Sunrise'],
      genre: [['Shounen'], ['Seinen'], ['Action']],
      score: [8.9],
      ranked: 1,
      popularity: 2453,
      openingTheme: ['yeah'],
      endingTheme: ['wow'],
    },
    {
      id: 32281,
      title: 'Kimi No Nawa',
      linkCanonical: '',
      imageUrl: 'https://myanimelist.cdn-dena.com/images/anime/7/79999.jpg',
      synopsis: '',
      type: '',
      episodes: 24,
      status: 'Airing',
      aired: '',
      producer: ['Sunrise'],
      studio: ['Sunrise'],
      genre: [['Shounen'], ['Seinen'], ['Action']],
      score: [8.9],
      ranked: 1,
      popularity: 2453,
      openingTheme: ['yeah'],
      endingTheme: ['wow'],
    },
    {
      id: 5114,
      title: 'Fullmetal Alchemist: Brotherhood',
      linkCanonical: '',
      imageUrl: 'https://myanimelist.cdn-dena.com/images/anime/5/47421.jpg',
      synopsis: '',
      type: '',
      episodes: 24,
      status: 'Airing',
      aired: '',
      producer: ['Sunrise'],
      studio: ['Sunrise'],
      genre: [['Shounen'], ['Seinen'], ['Action']],
      score: [8.9],
      ranked: 1,
      popularity: 2453,
      openingTheme: ['yeah'],
      endingTheme: ['wow'],
    },
    {
      id: 28977,
      title: 'Gintama°',
      linkCanonical: '',
      imageUrl: 'https://myanimelist.cdn-dena.com/images/anime/3/72078.jpg',
      synopsis: '',
      type: '',
      episodes: 24,
      status: 'Airing',
      aired: '',
      producer: ['Sunrise'],
      studio: ['Sunrise'],
      genre: [['Shounen'], ['Seinen'], ['Action']],
      score: [8.9],
      ranked: 1,
      popularity: 2453,
      openingTheme: ['yeah'],
      endingTheme: ['wow'],
    },
    {
      id: 9253,
      title: 'Steins;Gate',
      linkCanonical: '',
      imageUrl: 'https://myanimelist.cdn-dena.com/images/anime/5/73199.jpg',
      synopsis: '',
      type: '',
      episodes: 24,
      status: 'Airing',
      aired: '',
      producer: ['Sunrise'],
      studio: ['Sunrise'],
      genre: [['Shounen'], ['Seinen'], ['Action']],
      score: [8.9],
      ranked: 1,
      popularity: 2453,
      openingTheme: ['yeah'],
      endingTheme: ['wow'],
    },
    {
      id: 4181,
      title: 'Clannad: After Story',
      linkCanonical: '',
      imageUrl: 'https://myanimelist.cdn-dena.com/images/anime/13/24647.jpg',
      synopsis: '',
      type: '',
      episodes: 24,
      status: 'Airing',
      aired: '',
      producer: ['Sunrise'],
      studio: ['Sunrise'],
      genre: [['Shounen'], ['Seinen'], ['Action']],
      score: [8.9],
      ranked: 1,
      popularity: 2453,
      openingTheme: ['yeah'],
      endingTheme: ['wow'],
    },
  ],
  isFetching: false,
};

export default (state = initialState, action: string) => {
  return state;
};
